#! /usr/bin/env python

import pprint
from imgsync import config, registry

c = config.Config()


# print config
if c.opts.print_config:
    c.pprint()

# print album list if possible
if c.opts.list:
    registry, album = registry.AlbumRegistry().new(c.opts.list, None)
    album.printAlbumList()

# we have one or more local paths, what will we do with them?
elif c.opts.local:
    for local_album in c.opts.local:

        # load cache info if possible
        regcache, cache = registry.AlbumRegistry().new('local', local_album)
        if cache.exists():
            regcache.load()
            if c.opts.verbose:
                print "Cached Album Info"
                print "-----------------"
                pprint.pprint(regcache.dumpDict())
                print


        if c.opts.diff_with:

            if c.opts.diff_with == 'local':
                albumid = local_album
            else:
                albumid = getattr(c.opts, c.opts.diff_with + '_id')

            registry, album = registry.AlbumRegistry().new(c.opts.diff_with, albumid)

            album.scan()

            if c.opts.verbose:
                print "Scanned Album Info"
                print "------------------"
                pprint.pprint(registry.dumpDict())
                print

            diff = album.diff(cache)





