#! /usr/bin/env python

import pprint
from imgsync import config, album

c = config.Config()


if c['local']:
    from imgsync.handle_local import LocalAlbum
    for local_album in c['local']:
        album = LocalAlbum(local_album)
        if album.exists():
            album.load()

    if c.get('sync_to'):



    data = a.getAlbum()
    #pprint.pprint( a.album.dumpDict() )
    print a.album.dumps()



